--- 
apiVersion: v1
data: 
  mapRoles: |
      - rolearn: arn:aws:iam::486784706275:role/terraform-eks-demo-node
        username: system:node:{{EC2PrivateDNSName}}
        groups:
          - system:bootstrappers
          - system:nodes
  mapUsers: |
      - userarn: arn:aws:iam::486784706275:user/aws_gm 
        username: aws_gm 
        groups: 
          - system:masters
kind: ConfigMap
metadata: 
  name: aws-auth
  namespace: kube-system
