apiVersion: apps/v1
kind: Deployment 
metadata:
 name: sa-logic
 labels:
  app: sa-logic
spec:
 replicas: 2
 minReadySeconds: 15
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 1 
   maxSurge: 1 
 selector:
  matchLabels:
   app: sa-logic
 template:
  metadata:
   labels:
    app: sa-logic
  spec:
   containers:
   - image: CONTAINER_IMAGE
     imagePullPolicy: Always
     name: sa-logic
     ports:
     - containerPort: 5050
