apiVersion: apps/v1
kind: Deployment 
metadata:
 name: uber-be
 labels:
  app: uber-be
spec:
 replicas: 2
 minReadySeconds: 15
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 1 
   maxSurge: 1 
 selector:
  matchLabels:
   app: uber-be
 template:
  metadata:
   labels:
    app: uber-be
  spec:
   containers:
   - image: CONTAINER_IMAGE
     imagePullPolicy: Always
     name: uber-be
     ports:
     - containerPort: 80

